# Basic Information 
title: Kelly Zhu
position: MSc in Computer Science
affiliation: University of Toronto
email: zhu (at) cs.toronto.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: kelly zhu uoft
description: Kelly Zhu - Department of Computer Science
canonical: https://kellyzhu.ca

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=4k-1QxAAAAAJ&hl=en&oi=sra
cv_link: assets/files/CV.pdf
github_link: https://github.com/kellyzoo
linkedin: https://www.linkedin.com/in/kellyzhu-ca
# twitter: https://twitter.com/
youtube: https://www.youtube.com/@kellyzhu

# Images (e.g., your profile picture and your website's favicon) 
# "favicon_light" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
# favicon_light: ./assets/img/favicon_light.png
# favicon_dark: ./assets/img/favicon_dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# # Use this project as a remote theme for GitHub Pages
# # See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - README.md
#   - README_zh_Hans.md
#   - README_zh_Hant.md
#   - README_de.md
#   - LICENSE
#   - minimal-light.gemspec
#   - html_source_file/
